---
deployment:
  tasks:
    # Ruta de despliegue para toda la aplicación.
    - export DEPLOYPATH=/home/electroc/mesadeayuda.electrocreditosdelcauca.com/

    # Crea la carpeta de destino si no existe.
    - mkdir -p $DEPLOYPATH

    # Copia todos los archivos y carpetas del proyecto. Esto incluye la carpeta 'public'
    # y el nuevo .htaccess que está dentro de ella.
    - /bin/cp -R * $DEPLOYPATH
    